sudo: false

matrix:
  allow_failures:
    - python: nightly

  include:
    - os: linux
      python: 3.6.0

    - os: linux
      python: 3.6.1
      env: DEPLOY_DOCS=1

    - os: linux
      python: 3.6.1
      env: DEPLOY_PYPI=1

    - os: linux
      python: 3.6

    - os: linux
      python: nightly

    - os: linux
      python: 3.6.0
      env: TEST_CURIO=1

    - os: linux
      python: 3.6.1
      env: TEST_CURIO=1

    - os: linux
      python: 3.6
      env: TEST_CURIO=1

    - os: linux
      python: nightly
      env: TEST_CURIO=1

language: python

install:
  - pip install pip setuptools --upgrade
  - pip install .[dev]
  - pip install coveralls

script:
  - mypy --python-version 3.6 --disallow-untyped-calls --disallow-untyped-defs
    --warn-unused-ignores --show-traceback --strict-optional --ignore-missing-imports
    --follow-imports=skip --show-error-context --show-traceback -p sketchbook
  - flake8 .
  - coverage run --source=sketchbook setup.py test
  - sphinx-build -b html docs docs/_build/html

after_success:
  - coveralls

before_deploy:
  - if [[ "$DEPLOY_DOCS" == "1" ]]; then cd docs/_build/html; fi

deploy:
  - provider: s3
    access_key_id: AKIAJOZQYM7VD6BOZHCA
    secret_access_key:
      secure: "pz7jvSHiTjtym6Z+wXvYItSPrep09mWa5rBCtiDg3zAt4kvSVfrxK52WVElUCOLm2FPlOOpBYbMwWiIavmaGkP78Zq3wFbmbLLYTgMeStHbET7vViRbrNsghUyAsmO4savufYa6XSOcA0QKU8aD4UGzN23vvNfSkEzpdCu5GOX5Gc+OXYbzjHU38xeyTlMVtSMa3+rvWn8ZiXCu73I4pbYgD+D9FIEBH1ry5sE+xdvj8oo/r4ChVggaKEBeZjEXZqFru5Yf2O8ay185EU9IVPZU8laWnG5/kKRiT0PC/JK+ovoi5T+h6O5jAySi0RW5GaSMJ2XrT6tOgVjr+M+MtUjtRYVVMAoTbxYKV7Y5tzCi8QBQOv4IbDn7ylURMC1z4wFCx8d0jdttf9/khXHSw0Lwr5OrdbcImoo/88j8eZozsslE2ImPtXyMXhfZ2j1RDFMZnLf9K5k0Gewcdst8JkM6HApD04Z/z/4IcP1HJNliju6H4uZFhx76JzLXxhF4PNTGIZYZQxVUMr7RA1bR6pZ2Kr0AAOAV0aX4SQAau/S48LZO+24NgYopSJ4wFaNnROV3CUzsvmJ9Cu9s1T7RKrpK7NbY9i3irKZgo0KWTJYoTVeJrzKSq8/baXTDQvAe3hJPcJkZcXXjZpNXWCBvDdwP+0Nrk95fizypzYNyVKWE="
    bucket: "sketchbook-docs"
    skip_cleanup: true
    on:
      branch: master
      tags: false
      condition: "$DEPLOY_DOCS = 1"
    region: eu-west-2

  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://testpypi.python.org/pypi
    user: "futursolo"
    password:
      secure: "ePs6694cNLF5WMlMsiJjK4/P4DkiFJspmcpaNE+yQflrQEw15XKN1UJUc0VOyBFz7w7aFvyd4urOfalVYkB+VLfNRuXSg2D7A+DoHw8TeX0ZHtUdG+X7mNdBC3lKMXl1E8r2OizMO9g6Ac+3/Iz9GaTyYuIiZUEjA6fNdaCaOnKVJrybU3IGFrqfvC3NvrfXGiMrrV1+xlHFxku5Wypcv8Pv0eVH/6qbpoXoqxMaibq4Oeg64jIbr7fOhHS/wNgVb81gH1rHd7lCpj6pTwbObrO3J/GALH6W6D5BtXwcKnTIp9HH7QBm9XRC1aQRlJmpdoy4FR9PuSa9HZUrRjO2pZ6FmxgjEFzo0LtHj0Bdqmxvfn4HNrSqaWtwID1QzCNbkTrmGwEK4vhiAjRWeUdC38ysSIXc2rVSFyduefKpb5iAO5mXeq/bnCE5+yprbY0xn36EfGvrRDp5qmIMUmM7nhcv5vj6ftJmVz7+vzGbcOhUP8UnUJ+VDdFe6Waxk0PqKZ0Ho+221Fp2fo94JDvDCwlxsfN61jOQ2dvTfgEZ7jVAaLzdRKRiV+Cl+flMEdJYiYmLdtSu1T3ioodim5FoQlFzEZyFuXNtCyFDalWFv9t9Cgohk6xk4l6AoAlooi4944owryic+gGmxj9/r0umFbxYm6Y1xMgeCGK8nhoJVUg="
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: master
      tags: false
      condition: "$DEPLOY_PYPI = 1"

  - provider: pypi
    distributions: sdist bdist_wheel
    user: "futursolo"
    password:
      secure: "24RecZs9nFgSuhueAYulIMSQ5XHQd8UQN9Gx0KX6VUMw/2spuJgMuEOnRNc/sOJg4Pmw/FG5RykxnC6EWFU70cb9c3n2sdtqxOpHVA7Lqs6I47a90Ce6viiRm4yBW93M0yJzKQ8lDmC5FMLQvd8RWNgr3DPxHGoh69/+/eTFa3f/1QI3dZNcXIJr24LWmTTg2z3nwhf4eqrDRi23mEis/Rm/+ItVWe++0Qp1cSER+Fer7Saotibk4SKO1d5UzkuCBz1KUP3iQ/Y439QimQDxe1J1QoAncb0JaOdN2zANeoFZUrqdUdKWRlWDl4+CHRYbqJXOXD5siMo7f3+6q9Ys0Pg11l4s/fEO0r2XQ14zhV0OQOoYD4F3iJmKxLrBxU9XLr2Fq77xYXR3Vp4jGw7sYpId27ugZXBe/hT++nqFvKtbpCiam56CvNwGAtSfmKwRN3Wdqi9t/IOyXWk1b2Rg4PaMVbBYmtyonu2onzpNlCwWPQGX/dDv6Xy20FrVvGQR2aotPhdeqE08O3vkDaRdFZphb2EGY/jl3mN+aKPY8xygOGWQm43vt9eJzo21C55yTxP4qGZzTi7bqaeVCkbNP/FnlJVHzZgHktbupvWYE3W9LUpm/ltnRVgvB9dfLiIym9Kwl6fKsTyutzE9ue5+Nh2WwKImLFPSMmzWex9SXR0="
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: master
      tags: true
      condition: "$DEPLOY_PYPI = 1"
